-- Week 13: 种子化 af_sql_template（对齐 synthesis Claude.md）
-- keywords/params/tables_used 均为 JSON 列，必须用 JSON 数组字面量
-- 注意：flyway 当前禁用，需手动执行；重复执行会先 DELETE
DELETE FROM af_sql_template;

INSERT INTO af_sql_template (name, pattern, keywords, template_sql, params, category, example_question, tables_used, description, enabled, hit_count) VALUES
('收银宝交易总额', '总(交易|金额).*(收银宝|交易)', '["交易总额","收银宝","tranamt"]', 'SELECT SUM(tranamt) AS total_amount, SUM(amount) AS total_count FROM syb_transuminfor WHERE settledate BETWEEN {start_date} AND {end_date}', '["start_date","end_date"]', 'aggregate', '收银宝上个月交易总额', '["syb_transuminfor"]', '收银宝按日汇总表，settledate 为 int(yyyyMMdd)', 1, 0),
('收付通交易总额', '收付通.*交易|tlt', '["收付通","tlt","交易"]', 'SELECT SUM(tranamt) AS total_amount FROM tlt_transuminfor WHERE settledate BETWEEN {start_date} AND {end_date} AND transtype NOT IN (''结算-T+0代收付款'',''结算-代收付款'',''结算-代付失败退款'',''提现'')', '["start_date","end_date"]', 'aggregate', '收付通上月交易总额', '["tlt_transuminfor"]', '收付通需排除 4 类 transtype', 1, 0),
('交易类型分布', '(交易类型|transtype).*(分布|统计|排名)', '["交易类型","transtype"]', 'SELECT transtype, COUNT(*) AS cnt, SUM(tranamt) AS total_amount FROM syb_transuminfor WHERE settledate BETWEEN {start_date} AND {end_date} GROUP BY transtype ORDER BY total_amount DESC', '["start_date","end_date"]', 'groupby', '各交易类型的金额分布', '["syb_transuminfor"]', '字段是 transtype 不是 trantype', 1, 0),
('月度交易趋势', '(月度|按月|趋势).*(交易|金额)', '["月度","趋势","settledate DIV 100"]', 'SELECT settledate DIV 100 AS ym, SUM(tranamt) AS total_amount FROM syb_transuminfor WHERE settledate BETWEEN {start_date} AND {end_date} GROUP BY settledate DIV 100 ORDER BY ym', '["start_date","end_date"]', 'groupby', '按月的交易额趋势', '["syb_transuminfor"]', '取月份用 settledate DIV 100 整除', 1, 0),
('通联净收益', '(通联|净收益|收益).*(公司|部门)', '["通联收益","oldallinpayfee","allinpayfee"]', 'SELECT SUM(oldallinpayfee) AS company_income, SUM(allinpayfee) AS dept_income FROM syb_transuminfor WHERE settledate BETWEEN {start_date} AND {end_date}', '["start_date","end_date"]', 'aggregate', '通联净收益', '["syb_transuminfor"]', 'oldallinpayfee=公司口径，allinpayfee=部门口径', 1, 0),
('新增商户数', '(新增|新入网).*商户', '["新增商户","regdate","syb_merchant_rub"]', 'SELECT COUNT(DISTINCT cusid) AS new_count FROM (SELECT cusid FROM syb_merchant WHERE regdate BETWEEN ''{start_date}'' AND ''{end_date}'' UNION SELECT cusid FROM syb_merchant_rub WHERE regdate BETWEEN ''{start_date}'' AND ''{end_date}'') tmp', '["start_date","end_date"]', 'complex', '本月新增了多少商户', '["syb_merchant","syb_merchant_rub"]', '新增=正常+睡眠，按 regdate(varchar yyyy-MM-dd)，UNION 去重', 1, 0),
('存量正常商户', '(存量|正常).*商户', '["存量","state","正常"]', 'SELECT COUNT(*) AS exist_count FROM syb_merchant WHERE state = ''正常''', '[]', 'simple', '存量正常商户有多少', '["syb_merchant"]', '按 state=''正常'' 筛选', 1, 0),
('城市商户分布', '(城市|地区).*商户.*(分布|数量|排名)', '["城市","city","merchant"]', 'SELECT city, COUNT(*) AS merchant_count FROM syb_merchant GROUP BY city ORDER BY merchant_count DESC LIMIT 20', '[]', 'groupby', '各城市的商户数量分布', '["syb_merchant"]', 'city 在商户表', 1, 0),
('商户类型分布', '(商户类型|custype).*(分布|统计)', '["商户类型","custype"]', 'SELECT custype, COUNT(*) AS merchant_count FROM syb_merchant GROUP BY custype ORDER BY merchant_count DESC LIMIT 20', '[]', 'groupby', '各商户类型数量', '["syb_merchant"]', 'custype 字段', 1, 0),
('部门交易额', '(部门).*(交易|金额|交易额)', '["部门","organtbstart","dept_name"]', 'SELECT d.dept_name, SUM(t.tranamt) AS total_amount FROM (SELECT DISTINCT cusid, organtbstart FROM syb_merchantattribute) m INNER JOIN syb_transuminfor t ON t.cusid = m.cusid INNER JOIN sys_dept d ON d.dept_id = m.organtbstart WHERE t.settledate BETWEEN {start_date} AND {end_date} GROUP BY d.dept_name ORDER BY total_amount DESC', '["start_date","end_date"]', 'join', '各部门的收银宝交易金额', '["syb_merchantattribute","syb_transuminfor","sys_dept"]', '归属必须走 syb_merchantattribute，DISTINCT cusid 去重', 1, 0),
('三向归属利润', '(利润|收益).*(部门|归属)', '["利润","三向归属","startrate","endrate","allocationrate"]', 'SELECT dept_id, SUM(profit) AS total_profit FROM (SELECT organtbstart AS dept_id, SUM(allinpayfee*startrate) AS profit FROM syb_transuminfor s INNER JOIN syb_merchantattribute m ON s.cusid=m.cusid WHERE s.settledate BETWEEN {start_date} AND {end_date} GROUP BY organtbstart UNION ALL SELECT organtbend, SUM(allinpayfee*endrate) FROM syb_transuminfor s INNER JOIN syb_merchantattribute m ON s.cusid=m.cusid WHERE s.settledate BETWEEN {start_date} AND {end_date} GROUP BY organtbend UNION ALL SELECT allocationdept, SUM(allinpayfee*allocationrate) FROM syb_transuminfor s INNER JOIN syb_merchantattribute m ON s.cusid=m.cusid WHERE s.settledate BETWEEN {start_date} AND {end_date} GROUP BY allocationdept) tmp GROUP BY dept_id', '["start_date","end_date"]', 'complex', '各部门通联收益三向归属', '["syb_transuminfor","syb_merchantattribute"]', '拓展+维护+三方分润 UNION ALL', 1, 0),
('归属城市交易查询', '(归属|归属为|归属于).*(市|城市).*(交易|金额|交易额)', '["归属","organtbstart","dept_name","tranamt"]', 'SELECT d.dept_name, SUM(t.tranamt) AS total_amount FROM (SELECT DISTINCT cusid, organtbstart FROM syb_merchantattribute) a INNER JOIN syb_transuminfor t ON t.cusid = a.cusid INNER JOIN sys_dept d ON d.dept_id = a.organtbstart WHERE d.dept_name LIKE ''%{dept_keyword}%'' AND t.settledate BETWEEN {start_date} AND {end_date} GROUP BY d.dept_name', '["start_date","end_date","dept_keyword"]', 'join', '归属为南昌市的商户交易金额', '["syb_merchantattribute","syb_transuminfor","sys_dept"]', '"归属为XX市"="归属部门所在地"，不是商户city字段，必须走 syb_merchantattribute→sys_dept 关联链', 1, 0),
('归属部门商户统计', '(归属|归属为|归属于).*(部门|分公司).*(商户|数量)', '["归属","organtbstart","dept_name"]', 'SELECT d.dept_name, COUNT(DISTINCT a.cusid) AS merchant_count FROM syb_merchantattribute a INNER JOIN sys_dept d ON d.dept_id = a.organtbstart WHERE d.dept_name LIKE ''%{dept_keyword}%'' GROUP BY d.dept_name', '["dept_keyword"]', 'join', '归属为某部门的商户数量', '["syb_merchantattribute","sys_dept"]', '归属=organtbstart拓展部门，DISTINCT cusid去重', 1, 0),
('部门员工数', '(部门).*(员工|人数)', '["部门","员工","sys_user"]', 'SELECT d.dept_name, COUNT(u.user_id) AS user_count FROM sys_dept d LEFT JOIN sys_user u ON u.dept_id = d.dept_id WHERE d.status=''0'' AND d.del_flag=''0'' GROUP BY d.dept_id, d.dept_name ORDER BY user_count DESC', '[]', 'join', '各部门有多少员工', '["sys_dept","sys_user"]', 'dept_name/dept_id，status=0/del_flag=0', 1, 0),
('商户交易排名', '(商户).*(排名|TOP|前)', '["商户排名","cusname"]', 'SELECT m.cusname, SUM(t.tranamt) AS total_amount FROM syb_transuminfor t INNER JOIN syb_merchant m ON t.cusid=m.cusid WHERE t.settledate BETWEEN {start_date} AND {end_date} GROUP BY m.cusname ORDER BY total_amount DESC LIMIT 50', '["start_date","end_date"]', 'join', '交易额前10的商户', '["syb_transuminfor","syb_merchant"]', '交易关联商户取名称', 1, 0),
('流失商户', '(流失|沉默).*商户', '["流失","NOT IN"]', 'SELECT DISTINCT cusid FROM syb_transuminfor WHERE settledate BETWEEN {last_start} AND {last_end} AND cusid NOT IN (SELECT DISTINCT cusid FROM syb_transuminfor WHERE settledate BETWEEN {this_start} AND {this_end}) LIMIT 100', '["last_start","last_end","this_start","this_end"]', 'complex', '流失商户有哪些', '["syb_transuminfor"]', '上月有本月无', 1, 0),
('邮政商户', '(邮政).*商户', '["邮政","one"]', 'SELECT COUNT(*) AS post_count FROM syb_merchant WHERE one = ''20051300000023X''', '[]', 'simple', '邮政商户有多少', '["syb_merchant"]', '邮政标识 one=''20051300000023X''', 1, 0),
('客户层级商户', '(客户|标签).*(商户|数量)', '["客户","tag_pid","27"]', 'SELECT tag_name AS customer, COUNT(*) AS merchant_count FROM syb_merchant_tag WHERE tag_pid = 27 GROUP BY tag_name ORDER BY merchant_count DESC', '[]', 'groupby', '各客户名下商户数', '["syb_merchant_tag"]', '客户层级 tag_pid=27', 1, 0),
('工单状态分布', '(工单|订单).*(状态|分布)', '["工单","status","jxallinpay"]', 'SELECT status, COUNT(*) AS cnt FROM jxallinpay_busi_order GROUP BY status ORDER BY cnt DESC', '[]', 'groupby', '各状态工单数量', '["jxallinpay_busi_order"]', '工单表 status', 1, 0),
('工单城市分布', '(工单).*(城市|地区)', '["工单","city"]', 'SELECT city, COUNT(*) AS cnt FROM jxallinpay_busi_order GROUP BY city ORDER BY cnt DESC LIMIT 20', '[]', 'groupby', '各城市工单数量', '["jxallinpay_busi_order"]', '工单含 city 字段', 1, 0),
('工单业务类型', '(工单).*(业务类型|类型)', '["工单","busi_type"]', 'SELECT busi_type, COUNT(*) AS cnt FROM jxallinpay_busi_order GROUP BY busi_type ORDER BY cnt DESC', '[]', 'groupby', '各业务类型工单数', '["jxallinpay_busi_order"]', 'busi_type 字段', 1, 0),
('费率列表', '(费率|费率表)', '["费率","busi_rate","product_type"]', 'SELECT order_id, product_type, rate, status FROM busi_rate ORDER BY create_time DESC LIMIT 50', '[]', 'simple', '各产品费率', '["busi_rate"]', '费率表', 1, 0);
